stages:
    - build
    - build-artifact
    - publish
    - repository

default:
    image: docker:latest
    before_script: |
        DOCKER_TAG=${CI_COMMIT_REF_NAME/main/latest}
        DOCKER_TAG_PREFIX=$DOCKER_TAG-
        DOCKER_TAG_PREFIX=${DOCKER_TAG_PREFIX/latest-/}
        JAVA_VERSIONS=8
        if [ ! -z `command -v docker` ]; then
            echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_URL" ]; then echo -n $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_URL; fi
        fi
    after_script: |
        if [ ! -z `command -v docker` ]; then
            docker logout $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_URL" ]; then docker logout $DOCKER_REGISTRY_URL; fi
        fi

build:
    stage: build
    script:
        - for java_version in $JAVA_VERSIONS; do
              docker build . --pull --build-arg COMMIT_SHA=$CI_COMMIT_SHA --build-arg JAVA_VERSION=$java_version -t $CI_REGISTRY_IMAGE:${DOCKER_TAG_PREFIX}java$java_version;
              docker push $CI_REGISTRY_IMAGE:${DOCKER_TAG_PREFIX}java$java_version;
          done
        - docker tag $CI_REGISTRY_IMAGE:${DOCKER_TAG_PREFIX}java8 $CI_REGISTRY_IMAGE:$DOCKER_TAG
        - docker push $CI_REGISTRY_IMAGE:$DOCKER_TAG
    only:
        - branches
        - tags

create-gitlab-artifact-from-build:
    stage: build-artifact
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-docker-gitlab-build-artifact:latest
    script:
        - create-gitlab-artifact-from-docker-build $CI_REGISTRY_IMAGE:$DOCKER_TAG /$CI_PROJECT_NAME $CI_PROJECT_NAME-build.tar.gz
    artifacts:
        paths:
            - $CI_PROJECT_NAME-build.tar.gz
    only:
        - branches
        - tags

publish:
    stage: publish
    script:
        - for java_version in $JAVA_VERSIONS; do
              docker pull $CI_REGISTRY_IMAGE:${DOCKER_TAG_PREFIX}java$java_version;
              docker tag $CI_REGISTRY_IMAGE:${DOCKER_TAG_PREFIX}java$java_version $DOCKER_REGISTRY_URL/flux-ilias/ilserver-base:${DOCKER_TAG_PREFIX}java$java_version;
              docker push $DOCKER_REGISTRY_URL/flux-ilias/ilserver-base:${DOCKER_TAG_PREFIX}java$java_version;
          done
        - docker pull $CI_REGISTRY_IMAGE:$DOCKER_TAG
        - docker tag $CI_REGISTRY_IMAGE:$DOCKER_TAG $DOCKER_REGISTRY_URL/flux-ilias/ilserver-base:$DOCKER_TAG
        - docker push $DOCKER_REGISTRY_URL/flux-ilias/ilserver-base:$DOCKER_TAG
    only:
        - main
        - tags

flux-publish-utils:
    stage: repository
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-publish-utils:latest
    script:
        - publish-utils
    only:
        - main
